Mappings:
  RegionAmi:
    eu-central-1:
      ami: ami-0eb7496c2e0403237
    eu-west-2:
      ami: ami-0dd555eb7eb3b7c82
    us-east-1:
      ami: ami-033b95fb8079dc481
    us-west-1:
      ami: ami-0573b70afecda915d
  RegionKeyPair:
    eu-central-1:
      kp : frank-kp
    eu-west-2:
      kp : london-kp
    us-east-1:
      kp : virginia-kp
    us-west-1:
      kp : california-kp
Resources:
  MyEC2Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
        - S3FullAccess
  MyEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap
        - RegionAmi
        - !Ref AWS::Region
        - ami
      InstanceType: t2.micro
      SubnetId: subnet-047248decad3601e1
      IamInstanceProfile: !Ref MyEC2Profile
      SecurityGroupIds:
        - sg-07d32cda492864fe2
      KeyName: !FindInMap
        - RegionKeyPair
        - !Ref AWS::Region
        - kp
      UserData: !Base64 |
        #!/bin/bash
        yum update -y
        yum install httpd -y
        systemctl start httpd
        systemctl enable httpd
        cd /var/www/html
        aws s3 cp s3://dctpocos/names.csv ./
        aws s3 cp s3://dctpocos/index.txt ./
        EC2NAME=`cat ./names.csv|sort -R|head -n 1|xargs`
        sed "s/INSTANCE/$EC2NAME/" index.txt > index.html